name: Node.js Package

on:
  # Production trigger:
  release:
    types: [created]

  # Temporary testing trigger:
  # push:
  #   branches:
  #     - master

jobs:
  publish-npm:
    environment: publish-package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Verify package
        run: |
          node --version
          npm --version
          npm pkg get name version
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
